import { useAuth, useOrganization, useOrganizationList } from '@clerk/expo';
import { useLocalSearchParams, Link, useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ActivityIndicator, FlatList, Pressable, Text, TextInput, View } from 'react-native';
import { useState } from 'react';
import { mobileApi, Project, Task } from '../src/api';
import { MobileNav } from '../src/MobileNav';

export default function TasksScreen() {
  const { getToken } = useAuth(); const { organization } = useOrganization(); const { userMemberships } = useOrganizationList({ userMemberships: { pageSize: 20 } }); const params = useLocalSearchParams<{ projectId?: string }>(); const router = useRouter(); const queryClient = useQueryClient(); const [title, setTitle] = useState(''); const projectId = typeof params.projectId === 'string' ? params.projectId : '';
  const membershipId = userMemberships?.data?.find((membership) => membership.organization.id === organization?.id)?.id;
  const tasks = useQuery({ queryKey: ['mobile-tasks', organization?.id, projectId, membershipId], enabled: Boolean(organization?.id && membershipId), queryFn: async () => mobileApi.tasks((await getToken()) || '', { projectId: projectId || undefined, assigneeMembershipId: membershipId }) });
  const projects = useQuery({ queryKey: ['mobile-projects', organization?.id], enabled: Boolean(organization?.id), queryFn: async () => mobileApi.projects((await getToken()) || '') });
  const create = useMutation({ mutationFn: async () => { if (!projectId) throw new Error('Choose a project before adding a task.'); return mobileApi.createTask((await getToken()) || '', { projectId, title: title.trim() }); }, onSuccess: () => { setTitle(''); queryClient.invalidateQueries({ queryKey: ['mobile-tasks', organization?.id] }); } });
  const update = useMutation({ mutationFn: async ({ task, status }: { task: Task; status: string }) => mobileApi.updateTask((await getToken()) || '', task.id, { status }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['mobile-tasks', organization?.id] }) });
  if (tasks.isPending || projects.isPending) return <View className="flex-1 items-center justify-center bg-background"><ActivityIndicator /></View>;
  if (tasks.isError || projects.isError) return <View className="flex-1 items-center justify-center bg-background px-6"><Text className="mb-4 text-center text-red-700">{(tasks.error || projects.error)?.message}</Text><Pressable accessibilityRole="button" className="rounded-md border border-border px-4 py-3" onPress={() => { tasks.refetch(); projects.refetch(); }}><Text className="text-foreground">Try again</Text></Pressable></View>;
  const project = projects.data.projects.find((item) => item.id === projectId) as Project | undefined; const visibleTasks = tasks.data.tasks;
  return <View className="flex-1 bg-background px-4 pt-14"><View className="mb-4 flex-row items-center justify-between"><View><Text className="text-2xl font-bold text-foreground">My Work</Text><Text className="mt-1 text-muted">Tasks assigned in your workspace.</Text></View><Link href="/workspace" className="text-primary">Workspace</Link></View><View className="mb-5 rounded-lg border border-border bg-background p-3"><Text className="mb-2 font-semibold text-foreground">Add a task</Text><TextInput accessibilityLabel="Task title" className="min-h-11 rounded-md border border-border px-3 text-foreground" value={title} onChangeText={setTitle} placeholder="Task title" placeholderTextColor="#526270" /><Text className="mb-1 mt-3 text-sm text-muted">Project</Text><View className="flex-row flex-wrap gap-2">{projects.data.projects.map((item) => <Pressable key={item.id} accessibilityRole="radio" accessibilityState={{ selected: item.id === projectId }} onPress={() => router.setParams({ projectId: item.id })} className={`rounded-md border px-3 py-2 ${item.id === projectId ? 'border-primary bg-primary/10' : 'border-border'}`}><Text className="text-foreground">{item.name}</Text></Pressable>)}</View><Pressable accessibilityRole="button" accessibilityLabel="Create task" className="mt-3 min-h-11 items-center justify-center rounded-md bg-primary" onPress={() => create.mutate()} disabled={create.isPending || !title.trim() || !projectId}>{create.isPending ? <ActivityIndicator color="#fff" /> : <Text className="font-semibold text-white">Create task{project ? ` in ${project.name}` : ''}</Text>}</Pressable>{create.isError ? <Text accessibilityRole="alert" className="mt-2 text-red-700">{create.error.message}</Text> : null}</View><FlatList contentContainerStyle={{ paddingBottom: 88 }} data={visibleTasks} keyExtractor={(item) => item.id} ListEmptyComponent={<Text className="text-muted">{projectId ? 'No tasks in this project yet.' : 'No tasks assigned to you yet.'}</Text>} renderItem={({ item }: { item: Task }) => <View className="mb-3 rounded-lg border border-border bg-background p-4"><Link href={{ pathname: '/tasks/[taskId]', params: { taskId: item.id } }} asChild><Pressable accessibilityRole="button" accessibilityLabel={`Open task ${item.title}`}><Text className="font-semibold text-foreground">{item.title}</Text><Text className="mt-1 text-sm text-muted">{item.status} · {item.priority}{item.dueAt ? ` · due ${new Date(item.dueAt).toLocaleDateString()}` : ''}</Text></Pressable></Link><Pressable accessibilityRole="button" accessibilityLabel={`Mark ${item.title} ${item.status === 'done' ? 'to do' : 'done'}`} className="mt-3 self-start rounded-md border border-border px-3 py-2" onPress={() => update.mutate({ task: item, status: item.status === 'done' ? 'todo' : 'done' })} disabled={update.isPending}><Text className="text-foreground">{item.status === 'done' ? 'Reopen' : 'Mark done'}</Text></Pressable></View>} /><MobileNav /></View>;
}
