import { useAuth, useOrganization, useOrganizationList } from '@clerk/expo';
import { Link, useRouter } from 'expo-router';
import { useEffect } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';

export default function WorkspaceScreen() {
  const router = useRouter(); const { isSignedIn, signOut } = useAuth(); const { organization } = useOrganization(); const { isLoaded, userMemberships, setActive } = useOrganizationList({ userMemberships: { pageSize: 20 } });
  useEffect(() => { if (!isSignedIn) router.replace('/'); }, [isSignedIn, router]);
  if (!isSignedIn) return null;
  if (!isLoaded) return <View className="flex-1 items-center justify-center bg-background"><ActivityIndicator /></View>;
  if (!userMemberships?.data?.length) return <View className="flex-1 items-center justify-center bg-background px-6"><Text className="mb-2 text-xl font-semibold text-foreground">Create a workspace on the web</Text><Text className="mb-6 text-center text-muted">Mobile will show organizations after you create or join one.</Text><Pressable accessibilityRole="button" onPress={() => signOut()} className="rounded-lg border border-border px-4 py-3"><Text className="text-foreground">Sign out</Text></Pressable></View>;
  return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 32 }}><Text className="text-3xl font-bold text-foreground">Choose a workspace</Text><Text className="mt-2 text-muted">Select where you want to work. Switching refreshes your workspace data.</Text><View className="mt-7 gap-3">{userMemberships.data.map((membership) => { const selected = organization?.id === membership.organization.id; return <Pressable key={membership.organization.id} accessibilityRole="radio" accessibilityState={{ selected }} onPress={async () => { await setActive?.({ organization: membership.organization.id }); router.replace('/tasks'); }} className={`rounded-lg border p-4 ${selected ? 'border-primary bg-primary/10' : 'border-border bg-background'}`}><Text className="font-semibold text-foreground">{membership.organization.name}</Text><Text className="mt-1 text-sm text-muted">{selected ? 'Current workspace' : 'Open workspace'} · {membership.role || 'member'}</Text></Pressable>; })}</View><View className="mt-8 flex-row flex-wrap gap-2"><Link href="/tasks" asChild><Pressable className="rounded-md border border-border px-4 py-3"><Text className="text-foreground">My Work</Text></Pressable></Link><Link href="/ai" asChild><Pressable className="rounded-md border border-border px-4 py-3"><Text className="text-foreground">AI assistant</Text></Pressable></Link><Pressable accessibilityRole="button" onPress={() => signOut()} className="rounded-md border border-border px-4 py-3"><Text className="text-foreground">Sign out</Text></Pressable></View></ScrollView>;
}
