import { Link, useRouter } from 'expo-router';
import { useQueryClient } from '@tanstack/react-query';
import { useEffect } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { useWorkspace } from '../src/workspace';

export default function WorkspaceScreen() {
  const router = useRouter(); const queryClient = useQueryClient(); const { isSignedIn, signOut, activeWorkspace, workspaces, isLoaded, isLoadingWorkspaces, workspaceError, setActiveWorkspace } = useWorkspace();
  useEffect(() => { if (!isSignedIn) router.replace('/'); }, [isSignedIn, router]);
  if (!isSignedIn) return null;
  if (!isLoaded || isLoadingWorkspaces) return <View className="flex-1 items-center justify-center bg-background"><ActivityIndicator /></View>;
  if (workspaceError) return <View className="flex-1 items-center justify-center bg-background px-6"><Text accessibilityRole="alert" className="mb-5 text-center text-red-700">{workspaceError}</Text><Pressable accessibilityRole="button" onPress={() => signOut()} className="rounded-lg border border-border px-4 py-3"><Text className="text-foreground">Sign out</Text></Pressable></View>;
  if (!workspaces.length) return <View className="flex-1 items-center justify-center bg-background px-6"><Text className="mb-2 text-xl font-semibold text-foreground">Create a workspace on the web</Text><Text className="mb-6 text-center text-muted">Mobile will show organizations after you create or join one.</Text><Pressable accessibilityRole="button" onPress={() => signOut()} className="rounded-lg border border-border px-4 py-3"><Text className="text-foreground">Sign out</Text></Pressable></View>;
  return <ScrollView className="flex-1 bg-background px-5 pt-14" contentContainerStyle={{ paddingBottom: 32 }}><Text className="text-3xl font-bold text-foreground">Choose a workspace</Text><Text className="mt-2 text-muted">Select where you want to work. Switching refreshes your workspace data.</Text><View className="mt-7 gap-3">{workspaces.map((workspace) => { const selected = activeWorkspace?.id === workspace.id; return <Pressable key={workspace.id} accessibilityRole="radio" accessibilityState={{ selected }} onPress={async () => { if (selected) { router.replace('/tasks'); return; } await setActiveWorkspace(workspace.id); queryClient.clear(); router.replace('/tasks'); }} className={`rounded-[22px] border bg-surface p-4 ${selected ? 'border-primary bg-primary/10' : 'border-border'}`}><Text className="font-semibold text-foreground">{workspace.name}</Text><Text className="mt-1 text-sm text-muted">{selected ? 'Current workspace' : 'Open workspace'}</Text></Pressable>; })}</View><View className="mt-8 flex-row flex-wrap gap-2"><Link href="/tasks" asChild><Pressable className="rounded-xl border border-border bg-surface px-4 py-3"><Text className="text-foreground">My Work</Text></Pressable></Link><Link href="/ai" asChild><Pressable className="rounded-xl border border-border bg-surface px-4 py-3"><Text className="text-foreground">AI assistant</Text></Pressable></Link><Pressable accessibilityRole="button" onPress={() => signOut()} className="rounded-xl border border-border bg-surface px-4 py-3"><Text className="text-foreground">Sign out</Text></Pressable></View></ScrollView>;
}
